name: dbt_run_backfill_0_temp
run-name: dbt_run_backfill_0_temp

on:
  workflow_dispatch:
    branches:
      - "main"
  schedule:
    # Runs every 15 minutes
    - cron: "*/30 * * * *" 
      
    
env:
  DBT_PROFILES_DIR: "${{ vars.DBT_PROFILES_DIR }}"

  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE_XS }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  run_dbt_jobs:
    runs-on: ubuntu-latest
    environment: 
      name: workflow_prod

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "${{ vars.PYTHON_VERSION }}"
          cache: "pip"

      - name: install dependencies
        run: |
          pip install -r requirements.txt
          dbt deps
      - name: Run DBT Jobs
        run: |
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;
          dbt run -m models/bronze/bronze__updates_0.sql;


  notify-failure:
    needs: [run_dbt_jobs]
    if: failure()
    uses: ./.github/workflows/slack_notify.yml
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}         
